# src/spatial_migration/exceptions/custom_exceptions.py
class ExtractionError(Exception):
    """Raised when hay un error durante la extracci贸n de datos."""
    pass

class TransformationError(Exception):
    """Raised when hay un error durante la transformaci贸n de datos."""
    pass

class LoadError(Exception):
    """Raised when hay un error durante la carga de datos."""
    pass

class ValidationError(Exception):
    """Raised when los datos no pasan la validaci贸n."""
    pass

class ConfigurationError(Exception):
    """Raised when hay un error en la configuraci贸n."""
    pass
